In [11]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census 
from us import states

# Census API Key
from config import census_key
c = Census(census_key, year=2013)
# print(census_key)

f7df7ebf76ee7b191e8c6e14eac2de97234b1c5b

In [19]:
# Run Census Search to retrieve data on all zip codes 
# See: https://github.com/CommerceDataService/census-wrapper for library documentation
# See: https://gist.github.com/afhaque/60558290d6efd892351c4b64e5c01e9b for labels
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E", "B01002_002E",
                          "B01002_003E","B19301_001E"),
                           {'for': 'zip code tabulation area:*'})
                         
census_data
# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B01002_002E": "Median Male Age",
                                      "B01002_003E": "Median Female Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",                                      
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})
census_pd
                         

# # Add in Poverty Rate (Poverty Count / Population)
# census_pd["Poverty Rate"] = 100 * \
#     census_pd["Poverty Count"].astype(
#         int) / census_pd["Population"].astype(int)

# # Final DataFrame
# census_pd = census_pd[["Zipcode", "Population", "Median Age", "Household Income",
#                        "Per Capita Income", "Poverty Count", "Poverty Rate"]]

# # Visualize
# print(len(census_pd))
# census_pd.head()

,Name,Household Income,Population,Median Age,Median Male Age,Median Female Age,Per Capita Income,Zipcode
0,ZCTA5 08518,74286.0,5217.0,41.5,38.9,43.5,33963.0,08518
1,ZCTA5 08520,90293.0,27468.0,37.4,35.7,39.5,37175.0,08520
2,ZCTA5 08525,118656.0,4782.0,47.1,47.1,47.2,59848.0,08525
3,ZCTA5 08527,88588.0,54867.0,42.2,41.4,42.9,37021.0,08527
4,ZCTA5 08528,58676.0,245.0,48.5,49.5,47.0,49117.0,08528
...,...,...,...,...,...,...,...,...
33115,ZCTA5 99923,21944.0,81.0,64.3,64.1,64.4,17225.0,99923
33116,ZCTA5 99925,38125.0,668.0,46.4,41.7,47.3,25094.0,99925
33117,ZCTA5 99926,50052.0,1630.0,31.4,32.9,30.4,22850.0,99926
33118,ZCTA5 99927,19000.0,111.0,59.4,64.3,55.8,21157.0,99927
33119,ZCTA5 99929,45649.0,2341.0,53.1,52.9,53.4,28399.0,99929